/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App_Windows;

/**
 *
 * @author rony1
 */
public class LogIn_Window extends javax.swing.JFrame {

    /**
     * Creates new form Register_Window
     */
    public LogIn_Window() {
       this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_Button = new javax.swing.JButton();
        MenuBlack_Panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Email_Label = new javax.swing.JLabel();
        ForgotPassword_Label = new javax.swing.JLabel();
        Email_TextField = new javax.swing.JTextField();
        Password_TextField = new javax.swing.JTextField();
        Register_Buttton = new javax.swing.JButton();
        Password_Label = new javax.swing.JLabel();
        RegisterNow_Label = new javax.swing.JLabel();
        Banner_Label = new javax.swing.JLabel();
        LogIn_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setBorderPainted(false);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        MenuBlack_Panel.setBackground(new java.awt.Color(0, 0, 0));
        MenuBlack_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(147, 46, 236)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Email_Label.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
        Email_Label.setForeground(new java.awt.Color(255, 255, 255));
        Email_Label.setText("Email:");
        jPanel2.add(Email_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        ForgotPassword_Label.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        ForgotPassword_Label.setForeground(new java.awt.Color(255, 255, 255));
        ForgotPassword_Label.setText("Forgot your password?");
        jPanel2.add(ForgotPassword_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        Email_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Email_TextField.setForeground(new java.awt.Color(0, 0, 0));
        Email_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(147, 46, 236)));
        Email_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_TextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(Email_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, -1));

        Password_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Password_TextField.setForeground(new java.awt.Color(0, 0, 0));
        Password_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(147, 46, 236)));
        jPanel2.add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 290, -1));

        Register_Buttton.setBackground(new java.awt.Color(0, 159, 232));
        Register_Buttton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        Register_Buttton.setForeground(new java.awt.Color(255, 255, 255));
        Register_Buttton.setText("Log In");
        Register_Buttton.setBorder(null);
        Register_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButttonActionPerformed(evt);
            }
        });
        jPanel2.add(Register_Buttton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 460, 60));

        Password_Label.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
        Password_Label.setForeground(new java.awt.Color(255, 255, 255));
        Password_Label.setText("Password:");
        jPanel2.add(Password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        MenuBlack_Panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 530, 410));

        RegisterNow_Label.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        RegisterNow_Label.setForeground(new java.awt.Color(255, 240, 0));
        RegisterNow_Label.setText("Log In");
        MenuBlack_Panel.add(RegisterNow_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        Banner_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner.jpg"))); // NOI18N
        MenuBlack_Panel.add(Banner_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        getContentPane().add(MenuBlack_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 620, 720));

        LogIn_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogIn_Wallpaper.jpg"))); // NOI18N
        getContentPane().add(LogIn_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-620, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void Register_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButttonActionPerformed
    String email  = Email_TextField.getText();
    String password = Password_TextField.getText();
    
    Admin_Menu result = new Admin_Menu();
    dispose();
    result.setVisible(true);
    
    }//GEN-LAST:event_Register_ButttonActionPerformed

    private void Email_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner_Label;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JTextField Email_TextField;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel ForgotPassword_Label;
    private javax.swing.JLabel LogIn_Wallpaper;
    private javax.swing.JPanel MenuBlack_Panel;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JLabel RegisterNow_Label;
    private javax.swing.JButton Register_Buttton;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
