/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App_Windows;

/**
 *
 * @author rony1
 */
public class Users_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Menu
     */
    public Users_Menu() {
     this.setUndecorated(true);
     initComponents();
     Collection_InternalFrame.setVisible(false);
       AddPeople_InternalFrame.setVisible(false);
       LendItem_InternalFrame.setVisible(false);
       ReceiveItem_InternalFrame.setVisible(false); 
       ReviewItem_InternalFrame.setVisible(false);
       Queries_InternalFrame.setVisible(false);
       AddItem_InternalFrame.setVisible(false);
     
     this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Collection_InternalFrame = new javax.swing.JInternalFrame();
        Background_Panel = new javax.swing.JPanel();
        Title_Label = new javax.swing.JLabel();
        Subtitle_Label = new javax.swing.JLabel();
        Upper_Banner = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Collection_Table = new javax.swing.JTable();
        AddPeople_InternalFrame = new javax.swing.JInternalFrame();
        Background_Panel1 = new javax.swing.JPanel();
        Title_Label1 = new javax.swing.JLabel();
        Subtitle_Label1 = new javax.swing.JLabel();
        Upper_Banner1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PersonEmail_TextField = new javax.swing.JTextField();
        RelationType_Label = new javax.swing.JLabel();
        RelationType_ComboBox = new javax.swing.JComboBox<>();
        PersonEmail_Label = new javax.swing.JLabel();
        AddPeople_Button = new javax.swing.JButton();
        LendItem_InternalFrame = new javax.swing.JInternalFrame();
        Background_Panel2 = new javax.swing.JPanel();
        Title_Label2 = new javax.swing.JLabel();
        Subtitle_Label2 = new javax.swing.JLabel();
        Upper_Banner2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Day_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SelectIItem_ComboBox = new javax.swing.JComboBox<>();
        PersonEmail_Label2 = new javax.swing.JLabel();
        Lend_Button = new javax.swing.JButton();
        SelectITem_Label = new javax.swing.JLabel();
        PersonEmail_TextField2 = new javax.swing.JTextField();
        YellowTolerance_TextField = new javax.swing.JTextField();
        Month_TextField = new javax.swing.JTextField();
        ToleranceDays_Label = new javax.swing.JLabel();
        ReturnDate_Label = new javax.swing.JLabel();
        RedTolerance_TextField = new javax.swing.JTextField();
        Year_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ReceiveItem_InternalFrame = new javax.swing.JInternalFrame();
        Background_Panel3 = new javax.swing.JPanel();
        Title_Label3 = new javax.swing.JLabel();
        Subtitle_Label3 = new javax.swing.JLabel();
        Upper_Banner3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SelectIItem_ComboBox1 = new javax.swing.JComboBox<>();
        Receive_Button = new javax.swing.JButton();
        SelectITem_Label1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ReviewItem_InternalFrame = new javax.swing.JInternalFrame();
        Background_Panel4 = new javax.swing.JPanel();
        Title_Label4 = new javax.swing.JLabel();
        Subtitle_Label4 = new javax.swing.JLabel();
        Upper_Banner4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        SelectIItem_ComboBox2 = new javax.swing.JComboBox<>();
        Review_Button = new javax.swing.JButton();
        SelectItem_Label2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        SelectStars_Label = new javax.swing.JLabel();
        Queries_InternalFrame = new javax.swing.JInternalFrame();
        Background_Panel15 = new javax.swing.JPanel();
        Title_Label15 = new javax.swing.JLabel();
        Subtitle_Label15 = new javax.swing.JLabel();
        Upper_Banner15 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        Select_Label1 = new javax.swing.JLabel();
        SelectStdistic_ComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        Select_Label2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        AddItem_InternalFrame = new javax.swing.JInternalFrame();
        Background_Panel7 = new javax.swing.JPanel();
        Title_Label7 = new javax.swing.JLabel();
        Subtitle_Label7 = new javax.swing.JLabel();
        Upper_Banner7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ItemType_Label = new javax.swing.JLabel();
        Genre_TextField = new javax.swing.JComboBox<>();
        Genre_Label = new javax.swing.JLabel();
        ItemEdition_Label = new javax.swing.JLabel();
        ItemBarcode_Label = new javax.swing.JLabel();
        ItemTitle_Label = new javax.swing.JLabel();
        Publisher_Label1 = new javax.swing.JLabel();
        Publisher_ComboBox = new javax.swing.JComboBox<>();
        ItemType_TextField = new javax.swing.JTextField();
        ItemTitle_TextField = new javax.swing.JTextField();
        ItemEdition_TextField = new javax.swing.JTextField();
        ItemBarbcode_TextField = new javax.swing.JTextField();
        AddItem_Button = new javax.swing.JButton();
        AddPhoto_Button = new javax.swing.JButton();
        Menu_Panel = new javax.swing.JPanel();
        Divisor_Panel = new javax.swing.JPanel();
        Banner_Label = new javax.swing.JLabel();
        Lateral_Button1 = new javax.swing.JButton();
        Lateral_Button3 = new javax.swing.JButton();
        Lateral_Button4 = new javax.swing.JButton();
        Lateral_Button5 = new javax.swing.JButton();
        Lateral_Button6 = new javax.swing.JButton();
        Lateral_Button2 = new javax.swing.JButton();
        AddItem_Panel = new javax.swing.JPanel();
        AddAnItem_Button = new javax.swing.JButton();
        MainMenu_Button = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        Admin_Label = new javax.swing.JLabel();
        Wallpaper_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Collection_InternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        Collection_InternalFrame.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(233, 85, 4)));
        Collection_InternalFrame.setClosable(true);
        Collection_InternalFrame.setForeground(new java.awt.Color(255, 255, 255));
        Collection_InternalFrame.setMaximumSize(new java.awt.Dimension(900, 720));
        Collection_InternalFrame.setMinimumSize(new java.awt.Dimension(900, 720));
        Collection_InternalFrame.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        Collection_InternalFrame.setVisible(false);
        Collection_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background_Panel.setBackground(new java.awt.Color(102, 102, 102));
        Background_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Label.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Title_Label.setForeground(new java.awt.Color(255, 255, 255));
        Title_Label.setText("Your Collection!");
        Background_Panel.add(Title_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        Subtitle_Label.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Subtitle_Label.setForeground(new java.awt.Color(255, 255, 255));
        Subtitle_Label.setText("See your items and their current status...");
        Background_Panel.add(Subtitle_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        Upper_Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner3.png"))); // NOI18N
        Background_Panel.add(Upper_Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 100));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Collection_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Collection_Table);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 510));

        Background_Panel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 530));

        Collection_InternalFrame.getContentPane().add(Background_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        getContentPane().add(Collection_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 900, 720));

        AddPeople_InternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        AddPeople_InternalFrame.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 240, 0)));
        AddPeople_InternalFrame.setClosable(true);
        AddPeople_InternalFrame.setForeground(new java.awt.Color(255, 255, 255));
        AddPeople_InternalFrame.setMaximumSize(new java.awt.Dimension(900, 720));
        AddPeople_InternalFrame.setMinimumSize(new java.awt.Dimension(900, 720));
        AddPeople_InternalFrame.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        AddPeople_InternalFrame.setVisible(false);
        AddPeople_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background_Panel1.setBackground(new java.awt.Color(102, 102, 102));
        Background_Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Label1.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Title_Label1.setForeground(new java.awt.Color(255, 255, 255));
        Title_Label1.setText("Add People!");
        Background_Panel1.add(Title_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        Subtitle_Label1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Subtitle_Label1.setForeground(new java.awt.Color(255, 255, 255));
        Subtitle_Label1.setText("Family, friends, coworkers, everyone is here!");
        Background_Panel1.add(Subtitle_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        Upper_Banner1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner3.png"))); // NOI18N
        Background_Panel1.add(Upper_Banner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 100));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PersonEmail_TextField.setBackground(new java.awt.Color(255, 255, 255));
        PersonEmail_TextField.setForeground(new java.awt.Color(0, 0, 0));
        PersonEmail_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 240, 0)));
        jPanel1.add(PersonEmail_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, 30));

        RelationType_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        RelationType_Label.setForeground(new java.awt.Color(255, 255, 255));
        RelationType_Label.setText("Relation Type:");
        jPanel1.add(RelationType_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        RelationType_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        RelationType_ComboBox.setForeground(new java.awt.Color(0, 0, 0));
        RelationType_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family", "Friend", "Coworker" }));
        RelationType_ComboBox.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 240, 0)));
        jPanel1.add(RelationType_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 30));

        PersonEmail_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        PersonEmail_Label.setForeground(new java.awt.Color(255, 255, 255));
        PersonEmail_Label.setText("Person Email:");
        jPanel1.add(PersonEmail_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        AddPeople_Button.setBackground(new java.awt.Color(255, 240, 0));
        AddPeople_Button.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        AddPeople_Button.setForeground(new java.awt.Color(0, 0, 0));
        AddPeople_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonWhite.png"))); // NOI18N
        AddPeople_Button.setText("Add!");
        AddPeople_Button.setBorderPainted(false);
        AddPeople_Button.setContentAreaFilled(false);
        AddPeople_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(AddPeople_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 320, 100));

        Background_Panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 530));

        AddPeople_InternalFrame.getContentPane().add(Background_Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        getContentPane().add(AddPeople_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 900, 720));

        LendItem_InternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        LendItem_InternalFrame.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(242, 150, 0)));
        LendItem_InternalFrame.setClosable(true);
        LendItem_InternalFrame.setForeground(new java.awt.Color(255, 255, 255));
        LendItem_InternalFrame.setMaximumSize(new java.awt.Dimension(900, 720));
        LendItem_InternalFrame.setMinimumSize(new java.awt.Dimension(900, 720));
        LendItem_InternalFrame.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        LendItem_InternalFrame.setVisible(false);
        LendItem_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background_Panel2.setBackground(new java.awt.Color(102, 102, 102));
        Background_Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Label2.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Title_Label2.setForeground(new java.awt.Color(255, 255, 255));
        Title_Label2.setText("Lend Your Items!");
        Background_Panel2.add(Title_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        Subtitle_Label2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Subtitle_Label2.setForeground(new java.awt.Color(255, 255, 255));
        Subtitle_Label2.setText("Sharing never was so easy!");
        Background_Panel2.add(Subtitle_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        Upper_Banner2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner3.png"))); // NOI18N
        Background_Panel2.add(Upper_Banner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 100));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Day_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Day_TextField.setForeground(new java.awt.Color(0, 0, 0));
        Day_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(242, 150, 0)));
        jPanel2.add(Day_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 80, 30));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("yyyy             mm            dd");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        SelectIItem_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        SelectIItem_ComboBox.setForeground(new java.awt.Color(0, 0, 0));
        SelectIItem_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family", "Friend", "Coworker" }));
        SelectIItem_ComboBox.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(242, 150, 0)));
        jPanel2.add(SelectIItem_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 30));

        PersonEmail_Label2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        PersonEmail_Label2.setForeground(new java.awt.Color(255, 255, 255));
        PersonEmail_Label2.setText("Person Email:");
        jPanel2.add(PersonEmail_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        Lend_Button.setBackground(new java.awt.Color(255, 240, 0));
        Lend_Button.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Lend_Button.setForeground(new java.awt.Color(0, 0, 0));
        Lend_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonWhite.png"))); // NOI18N
        Lend_Button.setText("Lend-Izi!");
        Lend_Button.setBorderPainted(false);
        Lend_Button.setContentAreaFilled(false);
        Lend_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(Lend_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 320, 100));

        SelectITem_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        SelectITem_Label.setForeground(new java.awt.Color(255, 255, 255));
        SelectITem_Label.setText("Select Item:");
        jPanel2.add(SelectITem_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        PersonEmail_TextField2.setBackground(new java.awt.Color(255, 255, 255));
        PersonEmail_TextField2.setForeground(new java.awt.Color(0, 0, 0));
        PersonEmail_TextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(242, 150, 0)));
        jPanel2.add(PersonEmail_TextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 260, 30));

        YellowTolerance_TextField.setBackground(new java.awt.Color(255, 255, 255));
        YellowTolerance_TextField.setForeground(new java.awt.Color(0, 0, 0));
        YellowTolerance_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(242, 150, 0)));
        jPanel2.add(YellowTolerance_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 80, 30));

        Month_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Month_TextField.setForeground(new java.awt.Color(0, 0, 0));
        Month_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(242, 150, 0)));
        jPanel2.add(Month_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 80, 30));

        ToleranceDays_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        ToleranceDays_Label.setForeground(new java.awt.Color(255, 255, 255));
        ToleranceDays_Label.setText("Tolerance Days:");
        jPanel2.add(ToleranceDays_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        ReturnDate_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        ReturnDate_Label.setForeground(new java.awt.Color(255, 255, 255));
        ReturnDate_Label.setText("Return Date:");
        jPanel2.add(ReturnDate_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        RedTolerance_TextField.setBackground(new java.awt.Color(255, 255, 255));
        RedTolerance_TextField.setForeground(new java.awt.Color(0, 0, 0));
        RedTolerance_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(242, 150, 0)));
        jPanel2.add(RedTolerance_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 80, 30));

        Year_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Year_TextField.setForeground(new java.awt.Color(0, 0, 0));
        Year_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(242, 150, 0)));
        jPanel2.add(Year_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, 30));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("min               max");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 150, 30));

        Background_Panel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 530));

        LendItem_InternalFrame.getContentPane().add(Background_Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        getContentPane().add(LendItem_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 900, 720));

        ReceiveItem_InternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        ReceiveItem_InternalFrame.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 159, 232)));
        ReceiveItem_InternalFrame.setClosable(true);
        ReceiveItem_InternalFrame.setForeground(new java.awt.Color(255, 255, 255));
        ReceiveItem_InternalFrame.setMaximumSize(new java.awt.Dimension(900, 720));
        ReceiveItem_InternalFrame.setMinimumSize(new java.awt.Dimension(900, 720));
        ReceiveItem_InternalFrame.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        ReceiveItem_InternalFrame.setVisible(false);
        ReceiveItem_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background_Panel3.setBackground(new java.awt.Color(102, 102, 102));
        Background_Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Label3.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Title_Label3.setForeground(new java.awt.Color(255, 255, 255));
        Title_Label3.setText("Mark Your Items As Received!");
        Background_Panel3.add(Title_Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        Subtitle_Label3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Subtitle_Label3.setForeground(new java.awt.Color(255, 255, 255));
        Subtitle_Label3.setText("Stay in control ith your items!");
        Background_Panel3.add(Subtitle_Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        Upper_Banner3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner3.png"))); // NOI18N
        Background_Panel3.add(Upper_Banner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 100));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SelectIItem_ComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        SelectIItem_ComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        SelectIItem_ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family", "Friend", "Coworker" }));
        SelectIItem_ComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 159, 232)));
        jPanel3.add(SelectIItem_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 260, 30));

        Receive_Button.setBackground(new java.awt.Color(255, 240, 0));
        Receive_Button.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Receive_Button.setForeground(new java.awt.Color(0, 0, 0));
        Receive_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonWhite.png"))); // NOI18N
        Receive_Button.setText("Receive - Izi");
        Receive_Button.setBorderPainted(false);
        Receive_Button.setContentAreaFilled(false);
        Receive_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Receive_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Receive_ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(Receive_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 320, 100));

        SelectITem_Label1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        SelectITem_Label1.setForeground(new java.awt.Color(255, 255, 255));
        SelectITem_Label1.setText("Select Item:");
        jPanel3.add(SelectITem_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 400, 310));

        Background_Panel3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 530));

        ReceiveItem_InternalFrame.getContentPane().add(Background_Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        getContentPane().add(ReceiveItem_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 900, 720));

        ReviewItem_InternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        ReviewItem_InternalFrame.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(238, 141, 183)));
        ReviewItem_InternalFrame.setClosable(true);
        ReviewItem_InternalFrame.setForeground(new java.awt.Color(255, 255, 255));
        ReviewItem_InternalFrame.setMaximumSize(new java.awt.Dimension(900, 720));
        ReviewItem_InternalFrame.setMinimumSize(new java.awt.Dimension(900, 720));
        ReviewItem_InternalFrame.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        ReviewItem_InternalFrame.setVisible(false);
        ReviewItem_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background_Panel4.setBackground(new java.awt.Color(102, 102, 102));
        Background_Panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Label4.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Title_Label4.setForeground(new java.awt.Color(255, 255, 255));
        Title_Label4.setText("Review Your Items!");
        Background_Panel4.add(Title_Label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        Subtitle_Label4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Subtitle_Label4.setForeground(new java.awt.Color(255, 255, 255));
        Subtitle_Label4.setText("Stars means greatness");
        Background_Panel4.add(Subtitle_Label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        Upper_Banner4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner3.png"))); // NOI18N
        Background_Panel4.add(Upper_Banner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 100));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SelectIItem_ComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        SelectIItem_ComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        SelectIItem_ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        SelectIItem_ComboBox2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(238, 141, 183)));
        jPanel4.add(SelectIItem_ComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 260, 30));

        Review_Button.setBackground(new java.awt.Color(255, 240, 0));
        Review_Button.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Review_Button.setForeground(new java.awt.Color(0, 0, 0));
        Review_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonWhite.png"))); // NOI18N
        Review_Button.setText("Review!");
        Review_Button.setBorderPainted(false);
        Review_Button.setContentAreaFilled(false);
        Review_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Review_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Review_ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(Review_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 320, 100));

        SelectItem_Label2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        SelectItem_Label2.setForeground(new java.awt.Color(255, 255, 255));
        SelectItem_Label2.setText("Select Item:");
        jPanel4.add(SelectItem_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 720, 240));

        SelectStars_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        SelectStars_Label.setForeground(new java.awt.Color(255, 255, 255));
        SelectStars_Label.setText("Select Stars:");
        jPanel4.add(SelectStars_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        Background_Panel4.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 530));

        ReviewItem_InternalFrame.getContentPane().add(Background_Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        getContentPane().add(ReviewItem_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 900, 720));

        Queries_InternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        Queries_InternalFrame.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(13, 172, 103)));
        Queries_InternalFrame.setClosable(true);
        Queries_InternalFrame.setForeground(new java.awt.Color(0, 0, 0));
        Queries_InternalFrame.setMaximumSize(new java.awt.Dimension(900, 720));
        Queries_InternalFrame.setMinimumSize(new java.awt.Dimension(900, 720));
        Queries_InternalFrame.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        Queries_InternalFrame.setVisible(false);
        Queries_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background_Panel15.setBackground(new java.awt.Color(102, 102, 102));
        Background_Panel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Label15.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Title_Label15.setForeground(new java.awt.Color(255, 255, 255));
        Title_Label15.setText("Queries!");
        Background_Panel15.add(Title_Label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        Subtitle_Label15.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Subtitle_Label15.setForeground(new java.awt.Color(255, 255, 255));
        Subtitle_Label15.setText("See info about your collection...");
        Background_Panel15.add(Subtitle_Label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        Upper_Banner15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner3.png"))); // NOI18N
        Background_Panel15.add(Upper_Banner15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 100));

        jPanel16.setBackground(new java.awt.Color(51, 51, 51));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Select_Label1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Select_Label1.setForeground(new java.awt.Color(255, 255, 255));
        Select_Label1.setText("Parameters:");
        jPanel16.add(Select_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        SelectStdistic_ComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        SelectStdistic_ComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        SelectStdistic_ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Books by Genre", "Borrowed Books", "Borrowed Books by Genre", "Borroed Books by Age" }));
        SelectStdistic_ComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(13, 172, 103)));
        jPanel16.add(SelectStdistic_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 30));

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(jTable9);

        jPanel16.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 780, 360));

        Select_Label2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Select_Label2.setForeground(new java.awt.Color(255, 255, 255));
        Select_Label2.setText("Select:");
        jPanel16.add(Select_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(13, 172, 103)));
        jPanel16.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 110, 30));

        jButton1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Go!");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(13, 172, 103)));
        jButton1.setContentAreaFilled(false);
        jPanel16.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 40, 30));

        Background_Panel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 530));

        Queries_InternalFrame.getContentPane().add(Background_Panel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        getContentPane().add(Queries_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 900, 720));

        AddItem_InternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        AddItem_InternalFrame.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 255)));
        AddItem_InternalFrame.setClosable(true);
        AddItem_InternalFrame.setForeground(new java.awt.Color(0, 0, 0));
        AddItem_InternalFrame.setMaximumSize(new java.awt.Dimension(900, 720));
        AddItem_InternalFrame.setMinimumSize(new java.awt.Dimension(900, 720));
        AddItem_InternalFrame.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        AddItem_InternalFrame.setVisible(false);
        AddItem_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background_Panel7.setBackground(new java.awt.Color(102, 102, 102));
        Background_Panel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Label7.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        Title_Label7.setForeground(new java.awt.Color(255, 255, 255));
        Title_Label7.setText("Add an Item!");
        Background_Panel7.add(Title_Label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        Subtitle_Label7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Subtitle_Label7.setForeground(new java.awt.Color(255, 255, 255));
        Subtitle_Label7.setText("Expand your collection...");
        Background_Panel7.add(Subtitle_Label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        Upper_Banner7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner3.png"))); // NOI18N
        Background_Panel7.add(Upper_Banner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 100));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItemType_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        ItemType_Label.setForeground(new java.awt.Color(255, 255, 255));
        ItemType_Label.setText("Item Type:");
        jPanel8.add(ItemType_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        Genre_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Genre_TextField.setForeground(new java.awt.Color(0, 0, 0));
        Genre_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel8.add(Genre_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 260, 30));

        Genre_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Genre_Label.setForeground(new java.awt.Color(255, 255, 255));
        Genre_Label.setText("Genre:");
        jPanel8.add(Genre_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        ItemEdition_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        ItemEdition_Label.setForeground(new java.awt.Color(255, 255, 255));
        ItemEdition_Label.setText("Item Edition:");
        jPanel8.add(ItemEdition_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        ItemBarcode_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        ItemBarcode_Label.setForeground(new java.awt.Color(255, 255, 255));
        ItemBarcode_Label.setText("Item Barcode:");
        jPanel8.add(ItemBarcode_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        ItemTitle_Label.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        ItemTitle_Label.setForeground(new java.awt.Color(255, 255, 255));
        ItemTitle_Label.setText("Item Title:");
        jPanel8.add(ItemTitle_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Publisher_Label1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Publisher_Label1.setForeground(new java.awt.Color(255, 255, 255));
        Publisher_Label1.setText("Publisher:");
        jPanel8.add(Publisher_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        Publisher_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        Publisher_ComboBox.setForeground(new java.awt.Color(0, 0, 0));
        Publisher_ComboBox.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jPanel8.add(Publisher_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 260, 30));

        ItemType_TextField.setBackground(new java.awt.Color(255, 255, 255));
        ItemType_TextField.setForeground(new java.awt.Color(0, 0, 0));
        ItemType_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jPanel8.add(ItemType_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 30));

        ItemTitle_TextField.setBackground(new java.awt.Color(255, 255, 255));
        ItemTitle_TextField.setForeground(new java.awt.Color(0, 0, 0));
        ItemTitle_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jPanel8.add(ItemTitle_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 260, 30));

        ItemEdition_TextField.setBackground(new java.awt.Color(255, 255, 255));
        ItemEdition_TextField.setForeground(new java.awt.Color(0, 0, 0));
        ItemEdition_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jPanel8.add(ItemEdition_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 260, 30));

        ItemBarbcode_TextField.setBackground(new java.awt.Color(255, 255, 255));
        ItemBarbcode_TextField.setForeground(new java.awt.Color(0, 0, 0));
        ItemBarbcode_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jPanel8.add(ItemBarbcode_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 30));

        AddItem_Button.setBackground(new java.awt.Color(255, 240, 0));
        AddItem_Button.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        AddItem_Button.setForeground(new java.awt.Color(0, 0, 0));
        AddItem_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonWhite.png"))); // NOI18N
        AddItem_Button.setText("Add Item!");
        AddItem_Button.setBorderPainted(false);
        AddItem_Button.setContentAreaFilled(false);
        AddItem_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddItem_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItem_ButtonActionPerformed(evt);
            }
        });
        jPanel8.add(AddItem_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 320, 100));

        AddPhoto_Button.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        AddPhoto_Button.setForeground(new java.awt.Color(255, 255, 255));
        AddPhoto_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Photo_Icon64.png"))); // NOI18N
        AddPhoto_Button.setText("Add a Cover Image!");
        AddPhoto_Button.setBorderPainted(false);
        AddPhoto_Button.setContentAreaFilled(false);
        AddPhoto_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddPhoto_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(AddPhoto_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 270, 240));

        Background_Panel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 530));

        AddItem_InternalFrame.getContentPane().add(Background_Panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        getContentPane().add(AddItem_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 900, 720));

        Menu_Panel.setBackground(new java.awt.Color(0, 0, 0));
        Menu_Panel.setForeground(new java.awt.Color(0, 0, 0));
        Menu_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Divisor_Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Divisor_PanelLayout = new javax.swing.GroupLayout(Divisor_Panel);
        Divisor_Panel.setLayout(Divisor_PanelLayout);
        Divisor_PanelLayout.setHorizontalGroup(
            Divisor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        Divisor_PanelLayout.setVerticalGroup(
            Divisor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        Menu_Panel.add(Divisor_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 360, 3));

        Banner_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner.jpg"))); // NOI18N
        Menu_Panel.add(Banner_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 60));

        Lateral_Button1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Lateral_Button1.setForeground(new java.awt.Color(255, 255, 255));
        Lateral_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LateralButton1.png"))); // NOI18N
        Lateral_Button1.setText("         See Collection!");
        Lateral_Button1.setAlignmentX(5.0F);
        Lateral_Button1.setBorderPainted(false);
        Lateral_Button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lateral_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lateral_Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lateral_Button1MouseExited(evt);
            }
        });
        Lateral_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lateral_Button1ActionPerformed(evt);
            }
        });
        Menu_Panel.add(Lateral_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 170, 440, 60));

        Lateral_Button3.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Lateral_Button3.setForeground(new java.awt.Color(255, 255, 255));
        Lateral_Button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LateralButton3.png"))); // NOI18N
        Lateral_Button3.setText("Lend Item");
        Lateral_Button3.setAlignmentX(5.0F);
        Lateral_Button3.setBorderPainted(false);
        Lateral_Button3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lateral_Button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lateral_Button3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lateral_Button3MouseExited(evt);
            }
        });
        Lateral_Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lateral_Button3ActionPerformed(evt);
            }
        });
        Menu_Panel.add(Lateral_Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 290, 440, 60));

        Lateral_Button4.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Lateral_Button4.setForeground(new java.awt.Color(0, 0, 0));
        Lateral_Button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LateralButton4.png"))); // NOI18N
        Lateral_Button4.setText("      Receive Item");
        Lateral_Button4.setAlignmentX(5.0F);
        Lateral_Button4.setBorderPainted(false);
        Lateral_Button4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lateral_Button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lateral_Button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lateral_Button4MouseExited(evt);
            }
        });
        Lateral_Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lateral_Button4ActionPerformed(evt);
            }
        });
        Menu_Panel.add(Lateral_Button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 350, 440, 60));

        Lateral_Button5.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Lateral_Button5.setForeground(new java.awt.Color(255, 255, 255));
        Lateral_Button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LateralButton5.png"))); // NOI18N
        Lateral_Button5.setText("    Review Item");
        Lateral_Button5.setAlignmentX(5.0F);
        Lateral_Button5.setBorderPainted(false);
        Lateral_Button5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lateral_Button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lateral_Button5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lateral_Button5MouseExited(evt);
            }
        });
        Lateral_Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lateral_Button5ActionPerformed(evt);
            }
        });
        Menu_Panel.add(Lateral_Button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 410, 440, 60));

        Lateral_Button6.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Lateral_Button6.setForeground(new java.awt.Color(0, 0, 0));
        Lateral_Button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LateralButton6.png"))); // NOI18N
        Lateral_Button6.setText("  Do A Query");
        Lateral_Button6.setAlignmentX(5.0F);
        Lateral_Button6.setBorderPainted(false);
        Lateral_Button6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lateral_Button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lateral_Button6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lateral_Button6MouseExited(evt);
            }
        });
        Lateral_Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lateral_Button6ActionPerformed(evt);
            }
        });
        Menu_Panel.add(Lateral_Button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 470, 440, 60));

        Lateral_Button2.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Lateral_Button2.setForeground(new java.awt.Color(0, 0, 0));
        Lateral_Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LateralButton2.png"))); // NOI18N
        Lateral_Button2.setText("               Add known person");
        Lateral_Button2.setAlignmentX(5.0F);
        Lateral_Button2.setBorderPainted(false);
        Lateral_Button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lateral_Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lateral_Button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lateral_Button2MouseExited(evt);
            }
        });
        Lateral_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lateral_Button2ActionPerformed(evt);
            }
        });
        Menu_Panel.add(Lateral_Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 230, 440, 60));

        AddItem_Panel.setBackground(new java.awt.Color(204, 204, 204));
        AddItem_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddItem_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddItem_PanelMouseExited(evt);
            }
        });
        AddItem_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddAnItem_Button.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        AddAnItem_Button.setForeground(new java.awt.Color(51, 51, 51));
        AddAnItem_Button.setText("Add an Item!");
        AddAnItem_Button.setBorderPainted(false);
        AddAnItem_Button.setContentAreaFilled(false);
        AddAnItem_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddAnItem_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddAnItem_ButtonMouseExited(evt);
            }
        });
        AddAnItem_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAnItem_ButtonActionPerformed(evt);
            }
        });
        AddItem_Panel.add(AddAnItem_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 80));

        Menu_Panel.add(AddItem_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 270, 80));

        MainMenu_Button.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        MainMenu_Button.setForeground(new java.awt.Color(255, 255, 255));
        MainMenu_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home_Icon_32.png"))); // NOI18N
        MainMenu_Button.setText("Main         Menu");
        MainMenu_Button.setBorderPainted(false);
        MainMenu_Button.setContentAreaFilled(false);
        MainMenu_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainMenu_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenu_ButtonActionPerformed(evt);
            }
        });
        Menu_Panel.add(MainMenu_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 250, 40));

        getContentPane().add(Menu_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 720));

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setBorderPainted(false);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        Admin_Label.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Admin_Label.setForeground(new java.awt.Color(255, 255, 255));
        Admin_Label.setText("Admin");
        Admin_Label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Admin_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Admin_Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(Admin_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 60, 20));

        Wallpaper_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu_Wallpaper.png"))); // NOI18N
        getContentPane().add(Wallpaper_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lateral_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lateral_Button1ActionPerformed
     Collection_InternalFrame.setVisible(false);
       AddPeople_InternalFrame.setVisible(false);
       LendItem_InternalFrame.setVisible(false);
       ReceiveItem_InternalFrame.setVisible(false); 
       ReviewItem_InternalFrame.setVisible(false);
       Queries_InternalFrame.setVisible(false);
       AddItem_InternalFrame.setVisible(false);

       
       Collection_InternalFrame.setVisible(true);
       
    }//GEN-LAST:event_Lateral_Button1ActionPerformed

    private void Lateral_Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lateral_Button3ActionPerformed
      Collection_InternalFrame.setVisible(false);
       AddPeople_InternalFrame.setVisible(false);
       LendItem_InternalFrame.setVisible(false);
       ReceiveItem_InternalFrame.setVisible(false); 
       ReviewItem_InternalFrame.setVisible(false);
       Queries_InternalFrame.setVisible(false);
       AddItem_InternalFrame.setVisible(false);
       
       
       LendItem_InternalFrame.setVisible(true);
    }//GEN-LAST:event_Lateral_Button3ActionPerformed

    private void Lateral_Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lateral_Button4ActionPerformed
       Collection_InternalFrame.setVisible(false);
       AddPeople_InternalFrame.setVisible(false);
       LendItem_InternalFrame.setVisible(false);
       ReceiveItem_InternalFrame.setVisible(false); 
       ReviewItem_InternalFrame.setVisible(false);
       Queries_InternalFrame.setVisible(false);
       AddItem_InternalFrame.setVisible(false);
       
       ReceiveItem_InternalFrame.setVisible(true);        
    }//GEN-LAST:event_Lateral_Button4ActionPerformed

    private void Lateral_Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lateral_Button5ActionPerformed
       Collection_InternalFrame.setVisible(false);
       AddPeople_InternalFrame.setVisible(false);
       LendItem_InternalFrame.setVisible(false);
       ReceiveItem_InternalFrame.setVisible(false); 
       ReviewItem_InternalFrame.setVisible(false);
       Queries_InternalFrame.setVisible(false);
       AddItem_InternalFrame.setVisible(false);
       
       ReviewItem_InternalFrame.setVisible(true);    
    }//GEN-LAST:event_Lateral_Button5ActionPerformed

    private void Lateral_Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lateral_Button6ActionPerformed
       Collection_InternalFrame.setVisible(false);
       AddPeople_InternalFrame.setVisible(false);
       LendItem_InternalFrame.setVisible(false);
       ReceiveItem_InternalFrame.setVisible(false); 
       ReviewItem_InternalFrame.setVisible(false);
       Queries_InternalFrame.setVisible(false);
       AddItem_InternalFrame.setVisible(false);
       
       Queries_InternalFrame.setVisible(true);
    }//GEN-LAST:event_Lateral_Button6ActionPerformed

    private void Lateral_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lateral_Button2ActionPerformed
      Collection_InternalFrame.setVisible(false);
       AddPeople_InternalFrame.setVisible(false);
       LendItem_InternalFrame.setVisible(false);
       ReceiveItem_InternalFrame.setVisible(false); 
       ReviewItem_InternalFrame.setVisible(false);
       Queries_InternalFrame.setVisible(false);
       AddItem_InternalFrame.setVisible(false);

       
       AddPeople_InternalFrame.setVisible(true);
    }//GEN-LAST:event_Lateral_Button2ActionPerformed

    private void Lateral_Button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button1MouseEntered
        Lateral_Button1.setBounds(-60, 170, 440, 60);
    }//GEN-LAST:event_Lateral_Button1MouseEntered

    private void Lateral_Button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button1MouseExited
        Lateral_Button1.setBounds(-140, 170, 440, 60);
    }//GEN-LAST:event_Lateral_Button1MouseExited

    private void Lateral_Button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button2MouseEntered
        Lateral_Button2.setBounds(-60, 230, 440, 60);
    }//GEN-LAST:event_Lateral_Button2MouseEntered

    private void Lateral_Button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button2MouseExited
       Lateral_Button2.setBounds(-140, 230, 440, 60);
    }//GEN-LAST:event_Lateral_Button2MouseExited

    private void Lateral_Button3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button3MouseEntered
       Lateral_Button3.setBounds(-60, 290, 440, 60);
    }//GEN-LAST:event_Lateral_Button3MouseEntered

    private void Lateral_Button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button4MouseExited
     Lateral_Button4.setBounds(-140, 350, 440, 60);
    }//GEN-LAST:event_Lateral_Button4MouseExited

    private void Lateral_Button5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button5MouseEntered
       Lateral_Button5.setBounds(-60, 410, 440, 60);
    }//GEN-LAST:event_Lateral_Button5MouseEntered

    private void Lateral_Button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button4MouseEntered
        Lateral_Button4.setBounds(-60, 350, 440, 60);
    }//GEN-LAST:event_Lateral_Button4MouseEntered

    private void Lateral_Button3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button3MouseExited
       Lateral_Button3.setBounds(-140, 290, 440, 60);
    }//GEN-LAST:event_Lateral_Button3MouseExited

    private void Lateral_Button5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button5MouseExited
       Lateral_Button5.setBounds(-140, 410, 440, 60);
    }//GEN-LAST:event_Lateral_Button5MouseExited

    private void Lateral_Button6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button6MouseEntered
      Lateral_Button6.setBounds(-60, 470, 440, 60);
    }//GEN-LAST:event_Lateral_Button6MouseEntered

    private void Lateral_Button6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lateral_Button6MouseExited
      Lateral_Button6.setBounds(-140, 470, 440, 60);
    }//GEN-LAST:event_Lateral_Button6MouseExited

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
     System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void AddItem_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddItem_PanelMouseEntered
       
    }//GEN-LAST:event_AddItem_PanelMouseEntered

    private void AddItem_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddItem_PanelMouseExited
    
    }//GEN-LAST:event_AddItem_PanelMouseExited

    private void AddAnItem_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAnItem_ButtonActionPerformed
       Collection_InternalFrame.setVisible(false);
       AddPeople_InternalFrame.setVisible(false);
       LendItem_InternalFrame.setVisible(false);
       ReceiveItem_InternalFrame.setVisible(false); 
       ReviewItem_InternalFrame.setVisible(false);
       Queries_InternalFrame.setVisible(false);
       AddItem_InternalFrame.setVisible(false);
       
       AddItem_InternalFrame.setVisible(true);
    }//GEN-LAST:event_AddAnItem_ButtonActionPerformed

    private void AddAnItem_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddAnItem_ButtonMouseEntered
         AddItem_Panel.setBackground(new java.awt.Color(255,255,255));
         AddAnItem_Button.setForeground(new java.awt.Color(0,0,0));
         
         
    }//GEN-LAST:event_AddAnItem_ButtonMouseEntered

    private void AddAnItem_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddAnItem_ButtonMouseExited
         AddItem_Panel.setBackground(new java.awt.Color(204,204,204));
         AddAnItem_Button.setForeground(new java.awt.Color(51,51,51  ));
    }//GEN-LAST:event_AddAnItem_ButtonMouseExited

    private void MainMenu_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenu_ButtonActionPerformed
       Collection_InternalFrame.setVisible(false);
       AddPeople_InternalFrame.setVisible(false);
       LendItem_InternalFrame.setVisible(false);
       ReceiveItem_InternalFrame.setVisible(false); 
       ReviewItem_InternalFrame.setVisible(false);
       Queries_InternalFrame.setVisible(false);
       AddItem_InternalFrame.setVisible(false);

    }//GEN-LAST:event_MainMenu_ButtonActionPerformed

    private void Receive_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Receive_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Receive_ButtonActionPerformed

    private void Review_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Review_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Review_ButtonActionPerformed

    private void AddItem_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItem_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddItem_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAnItem_Button;
    private javax.swing.JButton AddItem_Button;
    private javax.swing.JInternalFrame AddItem_InternalFrame;
    private javax.swing.JPanel AddItem_Panel;
    private javax.swing.JButton AddPeople_Button;
    private javax.swing.JInternalFrame AddPeople_InternalFrame;
    private javax.swing.JButton AddPhoto_Button;
    private javax.swing.JLabel Admin_Label;
    private javax.swing.JPanel Background_Panel;
    private javax.swing.JPanel Background_Panel1;
    private javax.swing.JPanel Background_Panel15;
    private javax.swing.JPanel Background_Panel2;
    private javax.swing.JPanel Background_Panel3;
    private javax.swing.JPanel Background_Panel4;
    private javax.swing.JPanel Background_Panel7;
    private javax.swing.JLabel Banner_Label;
    private javax.swing.JInternalFrame Collection_InternalFrame;
    private javax.swing.JTable Collection_Table;
    private javax.swing.JTextField Day_TextField;
    private javax.swing.JPanel Divisor_Panel;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel Genre_Label;
    private javax.swing.JComboBox<String> Genre_TextField;
    private javax.swing.JTextField ItemBarbcode_TextField;
    private javax.swing.JLabel ItemBarcode_Label;
    private javax.swing.JLabel ItemEdition_Label;
    private javax.swing.JTextField ItemEdition_TextField;
    private javax.swing.JLabel ItemTitle_Label;
    private javax.swing.JTextField ItemTitle_TextField;
    private javax.swing.JLabel ItemType_Label;
    private javax.swing.JTextField ItemType_TextField;
    private javax.swing.JButton Lateral_Button1;
    private javax.swing.JButton Lateral_Button2;
    private javax.swing.JButton Lateral_Button3;
    private javax.swing.JButton Lateral_Button4;
    private javax.swing.JButton Lateral_Button5;
    private javax.swing.JButton Lateral_Button6;
    private javax.swing.JInternalFrame LendItem_InternalFrame;
    private javax.swing.JButton Lend_Button;
    private javax.swing.JButton MainMenu_Button;
    private javax.swing.JPanel Menu_Panel;
    private javax.swing.JTextField Month_TextField;
    private javax.swing.JLabel PersonEmail_Label;
    private javax.swing.JLabel PersonEmail_Label2;
    private javax.swing.JTextField PersonEmail_TextField;
    private javax.swing.JTextField PersonEmail_TextField2;
    private javax.swing.JComboBox<String> Publisher_ComboBox;
    private javax.swing.JLabel Publisher_Label1;
    private javax.swing.JInternalFrame Queries_InternalFrame;
    private javax.swing.JInternalFrame ReceiveItem_InternalFrame;
    private javax.swing.JButton Receive_Button;
    private javax.swing.JTextField RedTolerance_TextField;
    private javax.swing.JComboBox<String> RelationType_ComboBox;
    private javax.swing.JLabel RelationType_Label;
    private javax.swing.JLabel ReturnDate_Label;
    private javax.swing.JInternalFrame ReviewItem_InternalFrame;
    private javax.swing.JButton Review_Button;
    private javax.swing.JComboBox<String> SelectIItem_ComboBox;
    private javax.swing.JComboBox<String> SelectIItem_ComboBox1;
    private javax.swing.JComboBox<String> SelectIItem_ComboBox2;
    private javax.swing.JLabel SelectITem_Label;
    private javax.swing.JLabel SelectITem_Label1;
    private javax.swing.JLabel SelectItem_Label2;
    private javax.swing.JLabel SelectStars_Label;
    private javax.swing.JComboBox<String> SelectStdistic_ComboBox1;
    private javax.swing.JLabel Select_Label1;
    private javax.swing.JLabel Select_Label2;
    private javax.swing.JLabel Subtitle_Label;
    private javax.swing.JLabel Subtitle_Label1;
    private javax.swing.JLabel Subtitle_Label15;
    private javax.swing.JLabel Subtitle_Label2;
    private javax.swing.JLabel Subtitle_Label3;
    private javax.swing.JLabel Subtitle_Label4;
    private javax.swing.JLabel Subtitle_Label7;
    private javax.swing.JLabel Title_Label;
    private javax.swing.JLabel Title_Label1;
    private javax.swing.JLabel Title_Label15;
    private javax.swing.JLabel Title_Label2;
    private javax.swing.JLabel Title_Label3;
    private javax.swing.JLabel Title_Label4;
    private javax.swing.JLabel Title_Label7;
    private javax.swing.JLabel ToleranceDays_Label;
    private javax.swing.JLabel Upper_Banner;
    private javax.swing.JLabel Upper_Banner1;
    private javax.swing.JLabel Upper_Banner15;
    private javax.swing.JLabel Upper_Banner2;
    private javax.swing.JLabel Upper_Banner3;
    private javax.swing.JLabel Upper_Banner4;
    private javax.swing.JLabel Upper_Banner7;
    private javax.swing.JLabel Wallpaper_Label;
    private javax.swing.JTextField Year_TextField;
    private javax.swing.JTextField YellowTolerance_TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
