/*Autor: Renzo Barra, 5/25/2021*/
CREATE TABLE PE.ITEMTYPE (
	ITEMTYPE_ID INT COMMENT 'itemtype name.',
	ITEMTYPE_NAME VARCHAR(20),
	CREATION_DATE DATETIME,
	CREATION_USER VARCHAR(10),
	DATE_LAST_MODIFICATION DATETIME,
    USER_LAST_MODIFICATION VARCHAR(10)
    );

ALTER TABLE PE.ITEMTYPE  COMMENT 'Repository to storage information about ItemType.';

ALTER TABLE PE.ITEMTYPE
AUTO_INCREMENT = 0,
CHANGE COLUMN ITEMTYPE_ID ITEMTYPE_ID INT NOT NULL AUTO_INCREMENT COMMENT 'itemtype name.',
ADD PRIMARY KEY (ITEMTYPE_ID);

/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.ITEMTYPE_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.ITEMTYPE_BEFORE_INSERT BEFORE INSERT ON ITEMTYPE FOR EACH ROW
	BEGIN
		Set new.creation_date = SYSDATE();
		Set new.creation_user = USER();
		INSERT INTO systemLog(description, object, type_change)
		VALUES('AN ITEM TYPE IS INSERTED', 'ITEM TYPE', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.ITEMTYPE_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.ITEMTYPE_BEFORE_UPDATE BEFORE UPDATE ON ITEMTYPE FOR EACH ROW
	BEGIN
		Set new.date_last_modification= SYSDATE();
		Set new.user_last_modification= USER();
		INSERT INTO systemLog(description, object, type_change)
		VALUES('AN ITEM TYPE IS UPDATED', 'ITEM TYPE', 'UPDATE');
END$$
DELIMITER;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.ITEMTYPE_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.ITEMTYPE_BEFORE_DELETE BEFORE DELETE ON ITEMTYPE FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(description, object, type_change)
		VALUES('AN ITEM TYPE IS DELETED', 'ITEM TYPE', 'DELETE');
END$$