/*Autor: Renzo Barra, 5/25/2021*/
CREATE TABLE PE.PERSONCREATESITEM (
	PERSON_ID INT NOT NULL COMMENT 'Person identification code.', 
	ITEM_ID INT NOT NULL COMMENT 'Item identification code.', 
	CREATION_DATE DATETIME, 
	CREATION_USER VARCHAR(50), 
	DATE_LAST_MODIFICATION DATETIME, 
	USER_LAST_MODIFICATION VARCHAR(50)
    );

ALTER TABLE PE.PERSONCREATESITEM  COMMENT 'Repository to storage information the items a person creates.';

ALTER TABLE PE.PERSONCREATESITEM
	ADD PRIMARY KEY (PERSON_ID, ITEM_ID),
	ADD INDEX fk_personcreatesitem_item_id_idx (ITEM_ID ASC) VISIBLE;

/*======================================FOREIGN KEYS======================================*/
ALTER TABLE PE.PERSONCREATESITEM 
	ADD CONSTRAINT fk_personcreatesitem_person_id
	FOREIGN KEY (PERSON_ID)
	REFERENCES PE.PERSON (PERSON_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
    
	ADD CONSTRAINT fk_personcreatesitem_item_id
	FOREIGN KEY (ITEM_ID)
	REFERENCES PE.ITEM (ITEM_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;
    
/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSONCREATESITEM_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSONCREATESITEM_BEFORE_INSERT BEFORE INSERT ON PERSONCREATESITEM FOR EACH ROW
	BEGIN
		SET NEW.CREATION_DATE = SYSDATE();
		SET NEW.CREATION_USER = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON CREATES ITEM IS INSERTED', 'PERSON CREATES ITEM', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSONCREATESITEM_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSONCREATESITEM_BEFORE_UPDATE BEFORE UPDATE ON PERSONCREATESITEM FOR EACH ROW
	BEGIN
		SET NEW.DATE_LAST_MODIFICATION = SYSDATE();
		SET NEW.USER_LAST_MODIFICATION = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON CREATES ITEM IS UPDATED', 'PERSON CREATES ITEM', 'UPDATE');
END$$
DELIMITER;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSONCREATESITEM_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSONCREATESITEM_BEFORE_DELETE BEFORE DELETE ON PERSONCREATESITEM FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON CREATES ITEM IS DELETED', 'PERSON CREATES ITEM', 'DELETE');
END$$