/*Autor: Renzo Barra, 5/25/2021*/
CREATE TABLE PE.PERSON (
	PERSON_ID INT COMMENT 'Person identification code',
	FIRST_NAME VARCHAR(50) NOT NULL COMMENT 'Person first name.',
	LAST_NAME VARCHAR(50) NOT NULL COMMENT 'Person last name.',
	EMAIL VARCHAR(50) NOT NULL COMMENT 'Person email.',
	PASSWORD VARCHAR(50) NOT NULL COMMENT 'Person password.',
	PHONE_NUMBER VARCHAR(8) NOT NULL COMMENT 'Person phone number.',
	BIRTH_DAY DATETIME NOT NULL COMMENT 'Person birth day.',
	PERSONTYPE_ID INT COMMENT 'Person type identification.',
	CREATION_DATE DATETIME,
	CREATION_USER VARCHAR(50),
	DATE_LAST_MODIFICATION DATETIME,
	USER_LAST_MODIFICATION VARCHAR(50)
    );

ALTER TABLE PE.PERSON  COMMENT 'Repository to storage information about people in the database.';

ALTER TABLE PE.PERSON
AUTO_INCREMENT = 0,
CHANGE COLUMN PERSON_ID PERSON_ID INT NOT NULL COMMENT 'Person identification code',
ADD PRIMARY KEY (PERSON_ID);

/*======================================FOREIGN KEYS======================================*/
ALTER TABLE PE.PERSON
ADD INDEX fk_person_persontype_id_idx (PERSONTYPE_ID ASC) VISIBLE;

ALTER TABLE PE.PERSON 
	ADD CONSTRAINT fk_person_persontype_id
	FOREIGN KEY (PERSONTYPE_ID)
	REFERENCES PE.PERSONTYPE (PERSONTYPE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSON_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSON_BEFORE_INSERT BEFORE INSERT ON PERSON FOR EACH ROW
	BEGIN
		SET NEW.CREATION_DATE = SYSDATE();
		SET NEW.CREATION_USER = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON IS INSERTED', 'PERSON', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSON_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSON_BEFORE_UPDATE BEFORE UPDATE ON PERSON FOR EACH ROW
	BEGIN
		SET NEW.DATE_LAST_MODIFICATION = SYSDATE();
		SET NEW.USER_LAST_MODIFICATION = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON IS UPDATED', 'PERSON', 'UPDATE');
END$$
DELIMITER;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSON_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSON_BEFORE_DELETE BEFORE DELETE ON PERSON FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON IS DELETED', 'PERSON', 'DELETE');
END$$