/*Autor: Renzo Barra, 5/25/2021*/
CREATE TABLE PE.PUBLISHER (
	PUBLISHER_ID INT COMMENT 'publisher identification code.',
	PUBLISHER_NAME VARCHAR(50) COMMENT 'publisher name.',
	CREATION_DATE DATETIME,
	CREATION_USER VARCHAR(50),
	DATE_LAST_MODIFICATION DATETIME,
	USER_LAST_MODIFICATION VARCHAR(50)
    );

ALTER TABLE PE.PUBLISHER  COMMENT 'Repository to storage information about publishers.';

ALTER TABLE PE.PUBLISHER
AUTO_INCREMENT = 0,
CHANGE COLUMN PUBLISHER_ID PUBLISHER_ID INT NOT NULL AUTO_INCREMENT COMMENT 'publisher identification code.',
ADD PRIMARY KEY (PUBLISHER_ID);

/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.PUBLISHER_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PUBLISHER_BEFORE_INSERT BEFORE INSERT ON PUBLISHER FOR EACH ROW
	BEGIN
		SET NEW.CREATION_DATE = SYSDATE();
		SET NEW.CREATION_USER = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PUBLISHER IS INSERTED', 'PUBLISHER', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PUBLISHER_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PUBLISHER_BEFORE_UPDATE BEFORE UPDATE ON PUBLISHER FOR EACH ROW
	BEGIN
		SET NEW.DATE_LAST_MODIFICATION = SYSDATE();
		SET NEW.USER_LAST_MODIFICATION = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PUBLISHER IS UPDATED', 'PUBLISHER', 'UPDATE');
END$$
DELIMITER;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PUBLISHER_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PUBLISHER_BEFORE_DELETE BEFORE DELETE ON PUBLISHER FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PUBLISHER IS DELETED', 'PUBLISHER', 'DELETE');
END$$