/*Autor: Renzo Barra, 5/25/2021*/
CREATE TABLE PE.STATUS (
	STATUS_ID INT COMMENT 'status identification code.',
	STATUS_NAME VARCHAR(50) NOT NULL COMMENT 'status name.',
	DESCRIPTION VARCHAR(150) COMMENT 'status description.',
	CREATION_DATE DATETIME,
	CREATION_USER VARCHAR(50),
	DATE_LAST_MODIFICATION DATETIME,
	USER_LAST_MODIFICATION VARCHAR(50)
    );

ALTER TABLE PE.STATUS  COMMENT 'Repository to storage information about status.';

ALTER TABLE PE.STATUS
AUTO_INCREMENT = 0,
CHANGE COLUMN STATUS_ID STATUS_ID INT NOT NULL AUTO_INCREMENT COMMENT 'status identification code.',
ADD PRIMARY KEY (STATUS_ID);

/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.STATUS_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.STATUS_BEFORE_INSERT BEFORE INSERT ON STATUS FOR EACH ROW
	BEGIN
		Set new.creation_date = SYSDATE();
		Set new.creation_user = USER(); 
		INSERT INTO systemLog(description, object, type_change)
		VALUES('A STATUS IS INSERTED', 'STATUS', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.STATUS_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.STATUS_BEFORE_UPDATE BEFORE UPDATE ON STATUS FOR EACH ROW
	BEGIN
		Set new.date_last_modification= SYSDATE();
		Set new.user_last_modification= USER();
		INSERT INTO systemLog(description, object, type_change)
		VALUES('A STATUS IS UPDATED', 'STATUS', 'UPDATE');
END$$
DELIMITER;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.STATUS_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.STATUS_BEFORE_DELETE BEFORE DELETE ON STATUS FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(description, object, type_change)
		VALUES('A STATUS IS DELETED', 'STATUS', 'DELETE');
END$$