/*Autor: Renzo Barra, 5/25/2021*/

/*======================================TABLE======================================*/
CREATE TABLE PE.ITEMHASGENRE (
	ITEM_ID INT NOT NULL COMMENT 'Item identification code.',
	GENRE_ID INT NOT NULL COMMENT 'Genre identification code.',
	CREATION_DATE DATETIME,
	CREATION_USER VARCHAR(50),
	DATE_LAST_MODIFICATION DATETIME,
	USER_LAST_MODIFICATION VARCHAR(50)
    );

/*======================================COMMENTS======================================*/

ALTER TABLE PE.ITEMHASGENRE  COMMENT 'Repository to storage information about the Genres an Item has.';

/*======================================PRIMARY KEY======================================*/

ALTER TABLE PE.ITEMHASGENRE
	ADD PRIMARY KEY (ITEM_ID, GENRE_ID);

/*======================================FOREIGN KEYS======================================*/
ALTER TABLE PE.ITEMHASGENRE
ADD INDEX fk_itemhasgenre_genre_id_idx (GENRE_ID ASC) VISIBLE;

ALTER TABLE PE.ITEMHASGENRE
	ADD CONSTRAINT fk_itemhasgenre_genre_id
		FOREIGN KEY (GENRE_ID)
		REFERENCES PE.GENRE (GENRE_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	ADD CONSTRAINT fk_itemhasgenre_item_id
		FOREIGN KEY (ITEM_ID)
		REFERENCES PE.ITEM (ITEM_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;
    
/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.ITEMHASGENRE_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.ITEMHASGENRE_BEFORE_INSERT BEFORE INSERT ON ITEMHASGENRE FOR EACH ROW
	BEGIN
		SET NEW.CREATION_DATE = SYSDATE();
		SET NEW.CREATION_USER = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('AN ITEM HAS GENRE IS INSERTED', 'ITEM HAS GENRE', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.ITEMHASGENRE_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.ITEMHASGENRE_BEFORE_UPDATE BEFORE UPDATE ON ITEMHASGENRE FOR EACH ROW
	BEGIN
		SET NEW.DATE_LAST_MODIFICATION = SYSDATE();
		SET NEW.USER_LAST_MODIFICATION = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('AN ITEM HAS GENRE IS UPDATED', 'ITEM HAS GENRE', 'UPDATE');
END$$
DELIMITER;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.ITEMHASGENRE_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.ITEMHASGENRE_BEFORE_DELETE BEFORE DELETE ON ITEMHASGENRE FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('AN ITEM HAS GENRE IS DELETED', 'ITEM HAS GENRE', 'DELETE');
END$$