/*Autor: Renzo Barra, 5/25/2021*/

/*======================================TABLE======================================*/

CREATE TABLE PE.LOAN_HISTORY (
	LOAN_HISTORY_ID INT COMMENT 'loan_history  identification code.',
	PERSON1_ID INT COMMENT 'Person1 identification code.',
	PERSON2_ID INT COMMENT 'Person2 identification code.',
	ITEM_ID INT COMMENT 'Item identification code.',
	LEND_DATE DATETIME,
	RETURN_DATE DATETIME COMMENT 'Item Return Date.',
	AMOUNT_DAYS INT COMMENT 'Total amount of days.',
	TOLERANCE_DAYS_YELLOW INT COMMENT 'Item Return Tolerance Days Yellow.',
	TOLERANCE_DAYS_RED INT COMMENT 'Item Return Tolerance Days Red.',
	CREATION_DATE DATETIME,
	CREATION_USER VARCHAR(50),
	DATE_LAST_MODIFICATION DATETIME,
	USER_LAST_MODIFICATION VARCHAR(50)
    );

/*======================================COMMENTS======================================*/

ALTER TABLE PE.LOAN_HISTORY  COMMENT 'Repository to storage information about the items a person loan_history.';

/*======================================PRIMARY KEY======================================*/

ALTER TABLE PE.LOAN_HISTORY
	AUTO_INCREMENT = 0,
	CHANGE COLUMN LOAN_HISTORY_ID LOAN_HISTORY_ID INT NOT NULL AUTO_INCREMENT COMMENT 'loan_history  identification code.',
	ADD PRIMARY KEY (LOAN_HISTORY_ID);

/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.LOAN_HISTORY_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.LOAN_HISTORY_BEFORE_INSERT BEFORE INSERT ON LOAN_HISTORY FOR EACH ROW
	BEGIN
		SET NEW.CREATION_DATE = SYSDATE();
		SET NEW.CREATION_USER = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('AN LOAN HISTORY IS INSERTED', 'LOAN HISTORY', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.LOAN_HISTORY_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.LOAN_HISTORY_BEFORE_UPDATE BEFORE UPDATE ON LOAN_HISTORY FOR EACH ROW
	BEGIN
		SET NEW.DATE_LAST_MODIFICATION = SYSDATE();
		SET NEW.USER_LAST_MODIFICATION = USER();
		INSERT INTO systemlog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('AN LOAN HISTORY IS UPDATED', 'LOAN HISTORY', 'UPDATE');
END$$
DELIMITER;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.LOAN_HISTORY_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.LOAN_HISTORY_BEFORE_DELETE BEFORE DELETE ON LOAN_HISTORY FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)	
		VALUES('AN LOAN HISTORY IS DELETED', 'LOAN HISTORY', 'DELETE');
END$$