/*Autor: Renzo Barra, 5/25/2021*/

/*======================================TABLE======================================*/

CREATE TABLE PE.PERSONHASITEM (
	PERSON_ID INT NOT NULL COMMENT 'Person identification code.',
	ITEM_ID INT NOT NULL COMMENT 'Item identification code.',
	CREATION_DATE DATETIME,
	CREATION_USER VARCHAR(50),
	DATE_LAST_MODIFICATION DATETIME,
	USER_LAST_MODIFICATION VARCHAR(50)
    );

/*======================================COMMENTS======================================*/

ALTER TABLE PE.PERSONHASITEM  COMMENT 'Repository to storage information the items a person has.';

/*======================================PRIMARY KEY======================================*/

ALTER TABLE PE.PERSONHASITEM 
	ADD PRIMARY KEY (PERSON_ID, ITEM_ID),
	ADD INDEX fk_personhasitem_item_id_idx (ITEM_ID ASC) VISIBLE;

/*======================================FOREIGN KEYS======================================*/
ALTER TABLE PE.PERSONHASITEM
	ADD CONSTRAINT fk_personhasitem_person_id
	FOREIGN KEY (PERSON_ID)
	REFERENCES PE.PERSON (PERSON_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  
	ADD CONSTRAINT fk_personhasitem_item_id
	FOREIGN KEY (ITEM_ID)
	REFERENCES PE.ITEM (ITEM_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;
    
/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSONHASITEM_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSONHASITEM_BEFORE_INSERT BEFORE INSERT ON PERSONHASITEM FOR EACH ROW
	BEGIN
		SET NEW.CREATION_DATE = SYSDATE();
		SET NEW.CREATION_USER = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON HAS ITEM IS INSERTED', 'PERSON HAS ITEM', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSONHASITEM_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSONHASITEM_BEFORE_UPDATE BEFORE UPDATE ON PERSONHASITEM FOR EACH ROW
	BEGIN
		SET NEW.DATE_LAST_MODIFICATION = SYSDATE();
		SET NEW.USER_LAST_MODIFICATION = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON HAS ITEM IS UPDATED', 'PERSON HAS ITEM', 'UPDATE');
END$$
DELIMITER;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSONHASITEM_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSONHASITEM_BEFORE_DELETE BEFORE DELETE ON PERSONHASITEM FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON HAS ITEM IS DELETED', 'PERSON HAS ITEM', 'DELETE');
END$$