/*Autor: Renzo Barra, 5/25/2021*/

/*======================================TABLE======================================*/

CREATE TABLE PE.PERSONTYPE (
	PERSONTYPE_ID INT COMMENT 'Person Type identification code.',
	PERSONTYPE_NAME VARCHAR(50) NOT NULL COMMENT 'Person Type name.',
	CREATION_DATE DATETIME,
	CREATION_USER VARCHAR(50),
	DATE_LAST_MODIFICATION DATETIME,
	USER_LAST_MODIFICATION VARCHAR(50)
    );

/*======================================COMMENTS======================================*/

ALTER TABLE PE.PERSONTYPE  COMMENT 'Repository to storage information about the person types in the database.';

/*======================================PRIMARY KEY======================================*/

ALTER TABLE PE.PERSONTYPE
AUTO_INCREMENT = 0,
CHANGE COLUMN PERSONTYPE_ID PERSONTYPE_ID INT NOT NULL AUTO_INCREMENT COMMENT 'Person Type identification code.',
ADD PRIMARY KEY (PERSONTYPE_ID);

/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSONTYPE_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSONTYPE_BEFORE_INSERT BEFORE INSERT ON PERSONTYPE FOR EACH ROW
	BEGIN
		SET NEW.CREATION_DATE = SYSDATE();
		SET NEW.CREATION_USER = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON TYPE IS INSERTED', 'PERSON TYPE', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSONTYPE_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSONTYPE_BEFORE_UPDATE BEFORE UPDATE ON PERSONTYPE FOR EACH ROW
	BEGIN
		SET NEW.DATE_LAST_MODIFICATION = SYSDATE();
		SET NEW.USER_LAST_MODIFICATION = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON TYPE IS UPDATED', 'PERSON TYPE', 'UPDATE');
END$$
DELIMITER;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.PERSONTYPE_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.PERSONTYPE_BEFORE_DELETE BEFORE DELETE ON PERSONTYPE FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A PERSON TYPE IS DELETED', 'PERSON TYPE', 'DELETE');
END$$