/*Autor: Renzo Barra, 5/25/2021*/

/*======================================TABLE======================================*/

CREATE TABLE PE.REVIEW (
	REVIEW_ID INT COMMENT 'RelationType identification code.',
	STARS INT COMMENT 'Review stars.',
	CREATION_DATE DATETIME,
	CREATION_USER VARCHAR(50),
	DATE_LAST_MODIFICATION DATETIME,
	USER_LAST_MODIFICATION VARCHAR(50)
    );

/*======================================COMMENTS======================================*/

ALTER TABLE PE.REVIEW  COMMENT 'Repository to storage information about review.';

/*======================================PRIMARY KEY======================================*/

ALTER TABLE PE.REVIEW
AUTO_INCREMENT = 0,
CHANGE COLUMN REVIEW_ID REVIEW_ID INT NOT NULL AUTO_INCREMENT COMMENT 'RelationType identification code.',
ADD PRIMARY KEY (REVIEW_ID);

/*======================================TRIGGERS======================================*/
/*INSERT TRIGGER*/
DROP TRIGGER IF EXISTS PE.REVIEW_BEFORE_INSERT;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.REVIEW_BEFORE_INSERT BEFORE INSERT ON REVIEW FOR EACH ROW
	BEGIN
		SET NEW.CREATION_DATE = SYSDATE();
		SET NEW.CREATION_USER = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A REVIEW IS INSERTED', 'REVIEW', 'INSERT');
END$$
DELIMITER;

/*UPDATE TRIGGER*/
DROP TRIGGER IF EXISTS PE.REVIEW_BEFORE_UPDATE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.REVIEW_BEFORE_UPDATE BEFORE UPDATE ON REVIEW FOR EACH ROW
	BEGIN
		SET NEW.DATE_LAST_MODIFICATION = SYSDATE();
		SET NEW.USER_LAST_MODIFICATION = USER();
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A REVIEW IS UPDATED', 'REVIEW', 'UPDATE');
END$$
DELIMITER ;

/*DELETE TRIGGER*/
DROP TRIGGER IF EXISTS PE.review_BEFORE_DELETE;
DELIMITER $$
USE PE$$
CREATE DEFINER = CURRENT_USER TRIGGER PE.REVIEW_BEFORE_DELETE BEFORE DELETE ON REVIEW FOR EACH ROW
	BEGIN
		INSERT INTO systemLog(DESCRIPTION, OBJECT, TYPE_CHANGE)
		VALUES('A REVIEW IS DELETED', 'REVIEW', 'DELETE');
END$$