/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

/**
 *
 * @author pc
 */
public class Register_Window extends javax.swing.JFrame {

    /**
     * Creates new form Login_Window
     */
    public Register_Window() {
        this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Email_TextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        RegisterNow_Button = new javax.swing.JButton();
        First_Name_TextField = new javax.swing.JTextField();
        Last_Name_Label = new javax.swing.JLabel();
        Last_Name_TextField = new javax.swing.JTextField();
        Identification_Label = new javax.swing.JLabel();
        Identification_TextField = new javax.swing.JTextField();
        Phone_Number_Label = new javax.swing.JLabel();
        Phone_Number_TextField = new javax.swing.JTextField();
        Email_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        Password_TextField = new javax.swing.JTextField();
        Day_Month_Year_Label = new javax.swing.JLabel();
        Day_TextField = new javax.swing.JTextField();
        Month_TextField = new javax.swing.JTextField();
        Year_TextField = new javax.swing.JTextField();
        Birthday_Label = new javax.swing.JLabel();
        First_Name_Label1 = new javax.swing.JLabel();
        TopBar_Label1 = new javax.swing.JLabel();
        Log_in_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Email_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 350, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterNow_Button.setBackground(new java.awt.Color(147, 46, 236));
        RegisterNow_Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RegisterNow_Button.setForeground(new java.awt.Color(255, 255, 255));
        RegisterNow_Button.setText("Register Now!");
        RegisterNow_Button.setBorder(null);
        RegisterNow_Button.setBorderPainted(false);
        RegisterNow_Button.setFocusPainted(false);
        RegisterNow_Button.setFocusable(false);
        jPanel2.add(RegisterNow_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 140, 110));

        First_Name_TextField.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        First_Name_TextField.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel2.add(First_Name_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, -1));

        Last_Name_Label.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Last_Name_Label.setForeground(new java.awt.Color(0, 0, 0));
        Last_Name_Label.setText("Last Name:");
        jPanel2.add(Last_Name_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel2.add(Last_Name_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 350, -1));

        Identification_Label.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Identification_Label.setForeground(new java.awt.Color(0, 0, 0));
        Identification_Label.setText("Identification:");
        jPanel2.add(Identification_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel2.add(Identification_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 350, -1));

        Phone_Number_Label.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Phone_Number_Label.setForeground(new java.awt.Color(0, 0, 0));
        Phone_Number_Label.setText("Phone Number:");
        jPanel2.add(Phone_Number_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel2.add(Phone_Number_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 350, 20));

        Email_Label.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Email_Label.setForeground(new java.awt.Color(0, 0, 0));
        Email_Label.setText("Email:");
        jPanel2.add(Email_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        Password_Label.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Password_Label.setForeground(new java.awt.Color(0, 0, 0));
        Password_Label.setText("Password:");
        jPanel2.add(Password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));
        jPanel2.add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 350, -1));

        Day_Month_Year_Label.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Day_Month_Year_Label.setForeground(new java.awt.Color(0, 0, 0));
        Day_Month_Year_Label.setText("   dd            mm          yyyy");
        jPanel2.add(Day_Month_Year_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 140, 20));

        Day_TextField.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Day_TextFieldComponentShown(evt);
            }
        });
        jPanel2.add(Day_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 40, -1));
        jPanel2.add(Month_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 40, -1));
        jPanel2.add(Year_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 40, -1));

        Birthday_Label.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Birthday_Label.setForeground(new java.awt.Color(0, 0, 0));
        Birthday_Label.setText("Birthday:");
        jPanel2.add(Birthday_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        First_Name_Label1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        First_Name_Label1.setForeground(new java.awt.Color(0, 0, 0));
        First_Name_Label1.setText("First Name:");
        jPanel2.add(First_Name_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 510, 580));

        TopBar_Label1.setFont(new java.awt.Font("Arial Black", 0, 150)); // NOI18N
        TopBar_Label1.setForeground(new java.awt.Color(0, 159, 232));
        TopBar_Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Register_Now_logo.png"))); // NOI18N
        TopBar_Label1.setText("______");
        jPanel1.add(TopBar_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, 660, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 720));

        Log_in_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login_Wallpaper.jpg"))); // NOI18N
        getContentPane().add(Log_in_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Day_TextFieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Day_TextFieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Day_TextFieldComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Birthday_Label;
    private javax.swing.JLabel Day_Month_Year_Label;
    private javax.swing.JTextField Day_TextField;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JTextField Email_TextField;
    private javax.swing.JLabel First_Name_Label1;
    private javax.swing.JTextField First_Name_TextField;
    private javax.swing.JLabel Identification_Label;
    private javax.swing.JTextField Identification_TextField;
    private javax.swing.JLabel Last_Name_Label;
    private javax.swing.JTextField Last_Name_TextField;
    private javax.swing.JLabel Log_in_Wallpaper;
    private javax.swing.JTextField Month_TextField;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JLabel Phone_Number_Label;
    private javax.swing.JTextField Phone_Number_TextField;
    private javax.swing.JButton RegisterNow_Button;
    private javax.swing.JLabel TopBar_Label1;
    private javax.swing.JTextField Year_TextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
